### ISSUE TITLE
Can the Buffer definition be improved?

### ISSUE THREAD

**Issue by treeowl** [Bodigrim/linear-builder#1]
I noticed that you don't `UNPACK` the `Text` field in `Buffer`. That seems a bit surprising. If there's a reason for that, I think you should document it right there. Otherwise, change it!

**Comment by treeowl** [comment]
While you're at it, another interesting possibility might be to experiment with making `Buffer` unlifted in recent GHC. I doubt that'll lead to any difference in how it's compiled, but it may help avoid accidental laziness.

**Comment by Bodigrim** [comment]
Great point about `UNPACK`, done in https://github.com/Bodigrim/linear-builder/commit/36ae89686c7a0af5a0acfd8df00b41e5843f8470

Just for my education, what would it take to make `Buffer` unlifted? I have not yet looked at unlifted data types.

**Comment by treeowl** [comment]
Not much. I think just an `unlifted data Buffer`. But I'm not sure if there's been a release yet where worker wrapper works for unlifted stuff.

**Comment by Bodigrim** [comment]
I gave it a shot in https://github.com/Bodigrim/linear-builder/commit/0001684d2d9918cc399d05fa04d0ce86a1bbb805
It's a bit brittle to have `Buffer` lifted in GHC 9.0 and unlifted in GHC 9.2, but given how experimental this library is...
