### ISSUE TITLE
Unbox buffer

### ISSUE THREAD

**Issue by oberblastmeister** [Bodigrim/linear-builder#5]
See https://github.com/Bodigrim/linear-builder/issues/4#issuecomment-1470965392

**Comment by Bodigrim** [comment]
https://github.com/Bodigrim/linear-builder/blob/38c3587b65957bd4ae5393a98d9ec27f510875f6/src/Data/Text/Builder/Linear/Core.hs#L59-L60

It seems to me that it will be unpacked by GHC under the hood, no?

**Comment by oberblastmeister** [comment]
That just removes one level of indirection. The outer data constructor must still be allocated. The unboxed version has no indirection.

**Comment by Bodigrim** [comment]
Is this change compatible with linear types? 

It's difficult for me to validate without an example at hand.

**Comment by oberblastmeister** [comment]
I don't see why it wouldn't be compatible? I'm pretty sure linear types only affect arrows, so changing the kind of a type shouldn't matter.

**Comment by Bodigrim** [comment]
Could you possibly prepare a draft PR to discuss this with something substantial and measurable at hand?

**Comment by oberblastmeister** [comment]
If I do this, I would probably need to depend on `primitive`

**Comment by Bodigrim** [comment]
`primitive` is fine.

**Comment by Bodigrim** [comment]
If no one has resources to act on this issue, I'll close it as stalled in a month.
