### ISSUE TITLE
Improve benchmarks

### ISSUE THREAD

**Issue by oberblastmeister** [Bodigrim/linear-builder#6]
Builders should be used co-recursively, not as accumulators. Accumulators create long chains of closures, while co-recursion doesn't create any. This should probably also be added as a note to the README to help performance when using the builder interface.

**Comment by Bodigrim** [comment]
Could you possibly elaborate? I don't really know what "co-recursive" is.

**Comment by oberblastmeister** [comment]
```haskell
go (acc <> builder)
```

vs

```haskell
builder <> go
```

the latter should not allocate any closures

**Comment by Bodigrim** [comment]
I'm not sure that it's actually beneficial: strict builders perform better when parts are assembled by a strict left fold, not a lazy right one. Lazy builders are vice versa, so to make the task equally difficult the benchmarks append from both sides.

**Comment by oberblastmeister** [comment]
> I'm not sure that it's actually beneficial: strict builders perform better when parts are assembled by a strict left fold, not a lazy right one.

I don't think this is true. Lazy right folds mean that closures are not allocated, this is always faster than a strict left fold. It doesn't matter whether the builder output is lazy or not, you should always *use* a builder lazily.

> so to make the task equally difficult the benchmarks append from both sides.

This makes the 'co-recursive' version slightly worse, as we now have a recursive call. However, in my benchmarks, this was still faster than the accumulator version, probably because the overhead of a recursive call is still less than allocating closures.

**Comment by Bodigrim** [comment]
I'm happy to be proven wrong by data. I don't have a good mental model to hypothesize about it.

**Comment by Bodigrim** [comment]
If no one has resources to act on this issue, I'll close it as stalled in a month.
